global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'account_exporter'
    scrape_interval: 30s
    honor_labels: true
    metrics_path: /
    static_configs:
      - targets: ['account_exporter:8000']

  - job_name: 'position_exporter'
    scrape_interval: 30s
    honor_labels: true
    metrics_path: /
    static_configs:
      - targets: ['position_exporter:8001']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'