{
 "title": "Account Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Account Equity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "balance{balance_type=\"EQUITY\"}"
    }
   ]
  },
  {
   "title": "Buying Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "balance{balance_type=\"BUYING_POWER\"}"
    }
   ]
  },
  {
   "title": "Unrealized P/L",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(unrealized_pl)" }
   ]
  },
  {
   "title": "Change Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "change_today", "legendFormat": "{{symbol}}" }
   ]
  },
  {
   "title": "Market Value by Sector",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by (sector) (market_value)", "legendFormat": "{{sector}}" }
   ]
  },
  {
   "title": "Unrealized P/L by Position",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unrealized_pl", "legendFormat": "{{symbol}}" }
   ]
  },
  {
   "title": "Market Value by Position",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "market_value", "legendFormat": "{{symbol}}" }
   ]
  }
 ]
}